version: "3.9"
services:

  mariadb:
    image: mariadb:10.3.32
    container_name: db_carapi
    restart: always
    volumes:
      - mariadb-data:/var/lib/mysql
    ports:
      - 8201:3306
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin_carapi
    restart: always
    depends_on:
      - mariadb
    ports:
      - 8202:80
    environment:
      PMA_HOST: mariadb

  www:
    build: php
    container_name: www_carapi
    ports:
      - 8203:80
    volumes:
      - ./php/vhosts:/etc/apache2/sites-enabled
      - ../..:/var/www/carapi
    restart: always

volumes:
  mariadb-data: